management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics
  endpoint:
    health:
      show-details: always

info:
  app:
    name: FilmHub
    version: @project.version@

jwt:
  secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
  expiration: 86400000 # 24 hours in milliseconds

filmhub:
  base-url: https://api.film-hub.neofacto.dev